version: "3.8"
services:
  h2:
    image: "docker.io/buildo/h2database:2020-12-11"
    container_name: "h2"
    hostname: "h2"
    volumes:
      - "h2_data:/h2-data"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - netprojeto
  artifactory:
    image: "releases-docker.jfrog.io/jfrog/artifactory-oss:6.23.42"
    container_name: "artifactory"
    hostname: "artifactory"
    privileged: true
    user: "root"
    environment:
      - JF_ROUTER_ENTRYPOINTS_EXTERNALPORT=8082
    volumes:
      - "./artifactory/var:/var/opt/jfrog/artifactory"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    restart: always
    networks:
      - netprojeto
    depends_on:
      - h2
  jenkins:
    image: "docker.io/jenkins/jenkins:2.460-jdk17"
    container_name: "jenkins"
    hostname: "jenkins"
    privileged: true
    user: "root"
    volumes:
      - "jenkins_home:/var/jenkins_home"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - netprojeto
    depends_on:
      - artifactory
  gitlab:
    image: "docker.io/gitlab/gitlab-ce:12.10.14-ce.0"
    container_name: "gitlab"
    hostname: "fontes.localhost"
    restart: "always"
    volumes:
      - "./gitlab/config:/etc/gitlab"
      - "./gitlab/logs:/var/log/gitlab"
      - "./gitlab/data:/var/opt/gitlab"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - netprojeto
    depends_on:
      - jenkins
  sonarqube:
    image: "docker.io/sonarqube:9.9-community"
    container_name: "sonarqube"
    hostname: "sonarqube"
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - netprojeto
    depends_on:
      - jenkins
  tomcat:
    image: docker.io/tomcat:9.0.89-jre17
    container_name: tomcat
    hostname: "web.localhost"
    volumes:
      - ./tomcat/config/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - ./tomcat/webapps:/usr/local/tomcat/webapps
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - netprojeto
    depends_on:
      - sonarqube
  nginx:
    image: "docker.io/nginx:1.26.0-perl"
    container_name: "nginx"
    hostname: "nginx"
    ports:
      - "8000:80"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/proxyConf:/etc/nginx/conf.d"
      - "./nginx/html:/usr/share/nginx/html"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "nginx_log:/var/log/nginx"
    networks:
      - netprojeto
    depends_on:
      - tomcat
volumes:
  h2_data:
  jenkins_home:
  artifactory_var:
  gitlab_config:
  gitlab_log:
  gitlab_data:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:
  sonar_db:
  sonar_db_data:
  nginx_log:
networks:
  netprojeto:
    driver: bridge
